export const SET_CHECK_IN_DATE = 'SET_CHECK_IN_DATE';
export const SET_CHECK_OUT_DATE = 'SET_CHECK_OUT_DATE';
export const SET_LOCATION = 'SET_LOCATION';
export const ADD_GUEST = 'ADD_GUEST';
export const REMOVE_GUEST = 'REMOVE_GUEST';
export const SET_GUESTS = 'SET_GUESTS';
export const CLEAR_GUESTS = 'CLEAR_GUESTS';
export const SUBMIT_SEARCH = 'SUBMIT_SEARCH';

export const SET_CURRENT_HOME = 'SET_CURRENT_HOME';
export const SET_HOME_CHECK_IN_DATE = 'SET_HOME_CHECK_IN_DATE';
export const SET_HOME_CHECK_OUT_DATE = 'SET_HOME_CHECK_OUT_DATE';
export const CLEAR_HOME_CHECK_IN_DATE = 'CLEAR_HOME_CHECK_IN_DATE';
export const CLEAR_HOME_CHECK_OUT_DATE = 'CLEAR_HOME_CHECK_OUT_DATE';

export const SET_CENTER_MAP = 'SET_CENTER_MAP';

export const INIT_SIGN_UP_IN = 'INIT_SIGN_UP_IN';
export const SIGN_UP_IN_FAILED = 'SIGN_UP_IN_FAILED';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_OUT = 'SIGN_OUT';
export const CHECK_AUTH = 'CHECK_AUTH';
export const AUTH_NETWORK_ERROR = 'AUTH_NETWORK_ERROR';

export const FETCH_USER_LISTINGS = 'FETCH_USER_LISTINGS';

export const UPLOADING_IMAGE = 'UPLOADING_IMAGE';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const CREATE_LISTING = 'CREATE_LISTING';
export const SET_LISTING = 'SET_LISTING';
export const FETCH_LISTING = 'FETCH_LISTING';
export const SAVE_LISTING = 'SAVE_LISTING';
export const INIT_SAVE_LISTING = 'INIT_SAVE_LISTING';
export const DELETE_IMAGE = 'DELETE_IMAGE';

export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_FAILURE = 'CREATE_BOOKING_FAILURE';
export const INIT_CREATE_BOOKING = 'INIT_CREATE_BOOKING';
export const FETCH_BOOKINGS = 'FETCH_BOOKINGS';
export const INIT_FETCH_BOOKINGS = 'INIT_FETCH_BOOKINGS';
export const FETCH_BOOKINGS_SUCCESS = 'FETCH_BOOKINGS_SUCCESS';
export const FETCH_BOOKINGS_FAILURE = 'FETCH_BOOKINGS_FAILURE';
export const DENY_ACCEPT_SUCCESS = 'DENY_ACCEPT_SUCCESS';
export const INIT_DENY_ACCEPT_BOOKING = 'INIT_DENY_ACCEPT_BOOKING';