export const SET_CHECK_IN_DATE = 'SET_CHECK_IN_DATE';
export const SET_CHECK_OUT_DATE = 'SET_CHECK_OUT_DATE';
export const SET_LOCATION = 'SET_LOCATION';
export const ADD_GUEST = 'ADD_GUEST';
export const REMOVE_GUEST = 'REMOVE_GUEST';
export const CLEAR_GUESTS = 'CLEAR_GUESTS';